# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1sH0DO1lBQtZGWLVCbQDVQmsopxLGgU1v
"""

from google.colab import files
import pandas as pd

uploaded = files.upload()

import pandas as pd
#from pandas.tools import plotting
import matplotlib.pyplot as plt
import numpy as np
from sklearn.model_selection import train_test_split, cross_val_score, KFold, GridSearchCV
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier,export_graphviz
from sklearn.metrics import confusion_matrix, accuracy_score
from sklearn.ensemble import GradientBoostingClassifier, RandomForestClassifier

data_maol = pd.read_csv('/content/houseprice.csv', sep=';')
data_maol.head(5)

col_list=['Price']
numhouse = data_maol[data_maol.columns[data_maol.columns.isin(col_list)]]
plt.figure(figsize=(10,5))
numhouse.boxplot(sym='r*', grid=False)
plt.show()

plt.figure(figsize=(15,5))
plt.subplot(121)
data_maol['Price'].plot.hist(bins=10, title='Price')
plt.show()

col_list=['Price', 'SqFt']
numhouse = data_maol[data_maol.columns[data_maol.columns.isin(col_list)]]
numhouse.plot.scatter(x='SqFt', y='Price')

col_list=['Price', 'Bedrooms']
numhouse = data_maol[data_maol.columns[data_maol.columns.isin(col_list)]]
plt.figure(figsize=(15,5))
numhouse.boxplot(by='Bedrooms')
plt.show()

col_list=['Price', 'Bedrooms']
numhouse = data_maol[data_maol.columns[data_maol.columns.isin(col_list)]]
numhouse.plot.scatter(x='Bedrooms', y='Price')

col_list=['Price', 'Bathrooms']
numhouse = data_maol[data_maol.columns[data_maol.columns.isin(col_list)]]
numhouse.plot.scatter(x='Bathrooms', y='Price')

col_list=['Price', 'Bathrooms']
numhouse = data_maol[data_maol.columns[data_maol.columns.isin(col_list)]]
plt.figure(figsize=(15,5))
numhouse.boxplot(by='Bathrooms')
plt.show()